import litellm
import json

inp = input("You : ")

def multi(a,b):
    c = a * b
    return "This response is generated by tool calling" +" : " + str(c)

def add(a,b):
    c = a+b
    return "This is done by tool calling function"+" : "+str(c)

tool = [
      {
          "type": "function",
          "function": {
              "name": "multi",
              "description": "Multipliy two numbers and return the result as a string",
              "parameters": {
                  "type": "object",
                  "properties": {
                      "a": {
                          "type": "number",
                          "description": "First number"
                      },
                      "b": {
                          "type": "number",
                          "description": "Second number"
                      }
                  },
                  "required": ["a", "b"]
              }
          }
      },
      {
      "type": "function",
      "function": {
        "name": "add",
        "description": "Add two numbers and return the result as a string",
        "parameters": {
          "type": "object",
          "properties": {
            "a": {
              "type": "number",
              "description": "First number"
            },
            "b": {
              "type": "number",
              "description": "Second number"
            }
          },
          "required": ["a", "b"]
        }
      }
}
       ]

prompt = [
    {
        "role": "system",
        "content": "you are user-friendly assistant and understand the user-input and carefully find and call the tools which are required for full the user requirements.If needed call Multiple tools."
    },
    {"role" : "user", "content" : inp}
]

ollama = litellm.completion(
    base_url='http://localhost:11434',
    model='ollama/llama2',
    messages=prompt,
    tools=tool
)

fun_reg = {"add" : add ,
           "multi" : multi
           }

print(ollama.choices[0].finish_reason)

print(ollama.choices[0])

if ollama.choices[0].message.tool_calls:

    tool_calls_prmt= {"role" : "assistant" ,
                      "tool_calls": ollama.choices[0].message.tool_calls
                      }

    prompt.append(tool_calls_prmt)

    for Details in ollama.choices[0].message.tool_calls:

        fName = Details.function.name
        fArgs = json.loads(Details.function.arguments)
        fID = Details.id
        fun_get = fun_reg.get(fName)
        resp = fun_get(**fArgs)

        print("Tool is being called : " + fName)

        tool_message =  {
            "role" : "tool",
            "tool_call_id" : fID,
            "content" : resp
        }

        prompt.append(tool_message)

    ollama = litellm.completion(
        base_url='http://localhost:11434',
        model='ollama/llama2',
        messages=prompt
    )
    print("\n")
    print("Chat bot :" + ollama.choices[0].message.content)